baseURL = "https://cpaelzer.github.io/"
languageCode = "en-us"
title = "Pälzer"
theme = "minimal"
# not used yet
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Christian Ehrhardt"
    description = "because umlauts"
    copyright = "&copy; 2018 Christian Ehrhardt - Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)"
    githubUsername = "#cpaelzer"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "Bash", "Diff", "shell", "python", "C++", "yaml"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blogs/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/public_gpg.txt"
    name = "GPG Key"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:christian.ehrhardt@canonical.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/cpaelzer/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://launchpad.net/~paelzer"
    name = "linux"
    weight = 3


[[menu.icon]]
    url = "https://stackoverflow.com/users/6361589/christian-ehrhardt"
    name = "stack-overflow"
    weight = 4
